CREATE TABLE `account` (
    `id` INT NOT NULL AUTO_INCREMENT COMMENT '账号id',
    `username` VARCHAR(255) NOT NULL COMMENT '用户名',
    `password` VARCHAR(255) NOT NULL COMMENT '密码',
    `email` VARCHAR(255) NOT NULL COMMENT '邮箱',
    `phone` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '手机号',
    `sex` INT(11) DEFAULT 0 COMMENT '性别',
    `createAt` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `loginTimes` INT(11) DEFAULT 0 COMMENT '登录次数',
    `lastLoginAt` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '最后登录时间',
    `createAtIP` VARCHAR(255) NOT NULL COMMENT '创建IP',
    `lastLoginIP` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '最后登录IP',
    `state` INT(11) DEFAULT 0 COMMENT '状态',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `email_UNIQUE` (`email` ASC),
    UNIQUE INDEX `username_UNIQUE` (`username` ASC),
    UNIQUE INDEX `phone_UNIQUE` (`phone` ASC)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8 AUTO_INCREMENT=10086;